# --- !Ups

create table "users" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "username" varchar not null,
  "password" varchar not null
);

insert into "users" ("username", "password") values ('xittz', '1234');
insert into "users" ("username", "password") values ('admin', 'weqweq');

# --- !Downs

drop table "users" if exists;
